### ISSUE TITLE
support for implication on custom constraints

### ISSUE THREAD

**Issue by eileenyyang** [QuMuLab/bauhaus#92]
i.e. support for syntax
`e.add_constraint(a >> b)`

**Comment by haz** [comment]
> you can add the NNF form of the implication with add_constraint: a => b becomes e.add_constraint(~a | b)

This isn't already in place, is it? I.e., `e.add_constraint(a => b)` wouldn't fly.

1. I don't think we need to stay purely with NNF support (we can add more, but we should mirror the form if there's shared functionality -- just like `&` or `|`)
2. I'm fine with either `>>` or `=>`
3. Precisely -- just like we do with `~` (see [[here](https://github.com/QuMuLab/bauhaus/blob/main/bauhaus/core.py#L264)), which isn't handled by python-nnf like that.

**Comment by KarishmaDaga** [comment]
ah sorry that was badly phrased -- I meant that eileen should replace ``a >> b`` with the NNF form of the implication, so ``~a | b`` is passed in to add_constraint

gotcha, I think this will be nice to support! I'm leaning towards ``=>`` personally

@eileenyyang what do you think about the symbol? and would you be open to working on this feature? I'm happy to help out with any questions you have :)

**Comment by eileenyyang** [comment]
for sure, happy to start working on that. I'm good with either symbol, `=>` works great!

**Comment by haz** [comment]
Ah, right, I remember now why I suggested `>>` -- we don't have the option to do an operator overload on `=>`.

https://www.programiz.com/python-programming/operator-overloading

`__rshift__` is the one for `>>`

**Comment by eileenyyang** [comment]
ah ok sweet, thank you!

**Comment by haz** [comment]
Closed with #95
