### ISSUE TITLE
Big And/Or

### ISSUE THREAD

**Issue by haz** [QuMuLab/bauhaus#97]
Hey everyone,

Is there an easy way to create a big And/Or of a list of variables? I.e.

`fluents = []`
` term = And(fluents) >> x_a`

Thanks!

_Originally posted by @eileenyyang in https://github.com/QuMuLab/bauhaus/discussions/94_

**Comment by KarishmaDaga** [comment]
just approved the PR! it looks bueno and great feature request @eileenyyang !
